### ISSUE TITLE
Update Expiration time

### ISSUE THREAD

**Issue by Clotonervo** [Clotonervo/Event-Planner#64]
Right now an auth token expires in 15 seconds. It is important that we update it to expire after 15 minutes

**Comment by Gautam-Arora24** [comment]
May I work on this issue?

**Comment by Gautam-Arora24** [comment]
> Right now an auth token expires in 15 seconds. It is important that we update it to expire after 15 minutes

I checked on the server folder that there is already a commit stating these changes
