### ISSUE TITLE
Create App Bar Component

### ISSUE THREAD

**Issue by hokansom** [Clotonervo/Event-Planner#7]
This component will have include the logo in the top left, and the username at the top right. 

This element will have a fixed position, and it will always appear at the top of the page. 

![App Bar](https://user-images.githubusercontent.com/43146339/94981134-f1c5d800-04ec-11eb-8cef-015c2aa82e63.png)

**Comment by josiahsrc** [comment]
A note here, The <username> icon and text should be center aligned with the event planner. I messed that up on the designs.

**Comment by josiahsrc** [comment]
A note here, The "username" icon and text should be center aligned with the "event planner logo". I messed that up on the designs.
